### ISSUE TITLE
this node module is not compatible With electron v32 

### ISSUE THREAD

**Issue by debchy** [CatalystCode/electron-windows-notifications#15]
While building with electron-builder, I am getting bellow error:

```
preparing       moduleName=@nodert-win10-au/windows.applicationmodel arch=x64
  ⨯ 
  _nodert_generated.cpp
C:\Users\..\.electron-gyp\32.0.2\include\node\v8config.h(13,1): error C1189: #error:  "C++20 or later required." [E:\..\node_modules\@nodert-win10-au\windows.applicationmodel\build\binding.vcxproj]
Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
    at ChildProcess.onExit (E:\..\node_modules\@electron\rebuild\node_modules\node-gyp\lib\build.js:203:23)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)


  ⨯ node-gyp failed to rebuild 'E:\..\node_modules\@nodert-win10-au\windows.applicationmodel'  failedTask=build stackTrace=Error: node-gyp failed to rebuild 'E:\..\node_modules\@nodert-win10-au\windows.applicationmodel'
    at ChildProcess.<anonymous> (E:\..\node_modules\@electron\rebuild\lib\module-type\node-gyp\node-gyp.js:118:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by ZouJiu1** [comment]
the reason is the version of node is too high, you should downgrade the version to v20

brew install node@20

v22 is too higher

[https://zoujiu.com.cn](https://zoujiu.com.cn/#/csdn/markdown_detail/*?plan=/home/admin/vue-project/article/csdn_spider_selenium/article/2024-12-17_%E7%A9%BA%E6%A0%BC_21_50_10_Macos%E4%B8%8Anpm_%E7%A9%BA%E6%A0%BC_%E7%BC%96%E8%AF%91_%E7%A9%BA%E6%A0%BC_vscode%E6%8A%A5%E9%94%99%E4%BA%86_%E9%80%97%E5%8F%B7_%E5%85%B7%E4%BD%93%E7%9A%84%E6%98%AF%E7%89%88%E6%9C%AC%E5%A4%AA%E9%AB%98%E4%BA%86_%E9%80%97%E5%8F%B7_node-gyp_%E7%A9%BA%E6%A0%BC_C%2B%2B20_%E7%A9%BA%E6%A0%BC_or_%E7%A9%BA%E6%A0%BC_later_%E7%A9%BA%E6%A0%BC_required_%E7%A9%BA%E6%A0%BC_/2024-12-17_21_50_10_markdown.md)

[https://nodejs.org/zh-cn/download/package-manager](https://nodejs.org/zh-cn/download/package-manager)

**Comment by debchy** [comment]
> the reason is the version of node is too high, you should downgrade the version to v20
> 
> brew install node@20
> 
> v22 is too higher
> 
> [https://zoujiu.com.cn](https://zoujiu.com.cn/#/csdn/markdown_detail/*?plan=/home/admin/vue-project/article/csdn_spider_selenium/article/2024-12-17_%E7%A9%BA%E6%A0%BC_21_50_10_Macos%E4%B8%8Anpm_%E7%A9%BA%E6%A0%BC_%E7%BC%96%E8%AF%91_%E7%A9%BA%E6%A0%BC_vscode%E6%8A%A5%E9%94%99%E4%BA%86_%E9%80%97%E5%8F%B7_%E5%85%B7%E4%BD%93%E7%9A%84%E6%98%AF%E7%89%88%E6%9C%AC%E5%A4%AA%E9%AB%98%E4%BA%86_%E9%80%97%E5%8F%B7_node-gyp_%E7%A9%BA%E6%A0%BC_C%2B%2B20_%E7%A9%BA%E6%A0%BC_or_%E7%A9%BA%E6%A0%BC_later_%E7%A9%BA%E6%A0%BC_required_%E7%A9%BA%E6%A0%BC_/2024-12-17_21_50_10_markdown.md)
> 
> https://nodejs.org/zh-cn/download/package-manager

But I am also using node v20.17.0
